# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e26260cd46e8482097abaf1916ac417098ee0fd98663ffdac4496cf9afd2639109179322d2b724e701e4ec9222cfb03e15a0cdab125045a758a1e84a02c1eaa

test:
  secret_key_base: 22d12dc8a8f66beaa99063975eff40269d76ab58d08471ce2a1a61fd3d0b1ef408437950572969a98d78dc318a5077f16cf15ffa0d569b7135f04a9cb3c1b3f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
